"""
=========================================================
Base Repository
=========================================================

Author  : Athar Winda
Project : NLP for Opinion Classification and Aspect Processing

Description
-----------
Generic repository providing common CRUD
operations for SQLAlchemy ORM models.
"""

from __future__ import annotations

from typing import Generic, TypeVar

from sqlalchemy import (
    func,
    select,
)

from sqlalchemy.orm import (
    Session,
)

from database.base import Base


# =====================================================
# TYPE VARIABLES
# =====================================================

ModelType = TypeVar(
    "ModelType",
    bound=Base,
)


# =====================================================
# BASE REPOSITORY
# =====================================================

class BaseRepository(
    Generic[ModelType],
):
    """
    Generic repository for ORM models.
    """

    def __init__(
        self,
        session: Session,
        model: type[ModelType],
    ) -> None:

        self.session = session
        self.model = model

    # =================================================
    # CREATE
    # =================================================

    def add(
        self,
        instance: ModelType,
    ) -> ModelType:

        self.session.add(
            instance,
        )

        #
        # Push SQL so autogenerated IDs are available,
        # but DO NOT commit.
        #
        self.session.flush()

        self.session.refresh(
            instance,
        )

        return instance

    # =================================================
    # READ
    # =================================================

    def get(
        self,
        object_id: int,
    ) -> ModelType | None:

        return self.session.get(
            self.model,
            object_id,
        )

    def list(
        self,
    ) -> list[ModelType]:

        return list(

            self.session.scalars(

                select(
                    self.model,
                )

            )

        )

    def exists(
        self,
        object_id: int,
    ) -> bool:

        return (

            self.get(
                object_id,
            )

            is not None

        )

    def count(
        self,
    ) -> int:

        statement = (

            select(
                func.count(),
            )

            .select_from(
                self.model,
            )

        )

        return (

            self.session.scalar(
                statement,
            )

            or 0

        )

    # =================================================
    # UPDATE
    # =================================================

    def update(
        self,
        instance: ModelType,
    ) -> ModelType:

        #
        # Flush pending UPDATE statements.
        #
        self.session.flush()

        self.session.refresh(
            instance,
        )

        return instance

    # =================================================
    # DELETE
    # =================================================

    def delete(
        self,
        object_id: int,
    ) -> bool:

        instance = self.get(
            object_id,
        )

        if instance is None:

            return False

        self.session.delete(
            instance,
        )

        #
        # Flush pending DELETE statement.
        #
        self.session.flush()

        return True

    def delete_all(
        self,
    ) -> int:

        objects = self.list()

        count = len(
            objects,
        )

        for obj in objects:

            self.session.delete(
                obj,
            )

        self.session.flush()

        return count